(program ()
(define (cons e ls)
        (vector e ls))
(define (empty)
        (vector #f))
(define (car ls)
        (vector-ref ls 0))
(define (cdr ls)
        (vector-ref ls 1))
(car (cdr (cons 3 (cons 42 (cons 1 (empty)))))))
